# Generated by Django 3.1.2 on 2020-10-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojects',
            name='identity',
            field=models.TextField(null=True),
        ),
    ]
